CREATE TABLE PRODUCTOS(
    PRO_ID SERIAL PRIMARY KEY,
    PRO_NOMBRE VARCHAR(50),
    PRO_STOCK INT,
    PRO_PRECIO NUMERIC(10,2),
    PRO_CARACTERISTICAS TEXT,
    PRO_ESTADO VARCHAR(50),
    PRO_FECHA_CREACION TIMESTAMP,
    PRO_FECHA_ACTUALIZACION TIMESTAMP,
    PRO_STOCK_MINIMO INT,
    CHECK(PRO_ESTADO IN('ACTIVO','INACTIVO'))
);

CREATE TABLE USUARIOS(
    USU_ID SERIAL PRIMARY KEY,
    USU_NOMBRE VARCHAR(50),
    USU_EMAIL VARCHAR(50),
    USU_PASSWORD VARCHAR(50),
    USU_TIPO_DOCUMENTO VARCHAR(50),
    USU_NUMERO_DOCUMENTO VARCHAR(50),
    USU_ESTADO VARCHAR(50),
    USU_FECHA_CREACION TIMESTAMP,
    USU_FECHA_ACTUALIZACION TIMESTAMP,
    CHECK(USU_TIPO_DOCUMENTO IN('CC','CE','TI','NIT')),
    CHECK(USU_ESTADO IN('ACTIVO','INACTIVO'))
);

CREATE TABLE INVENTARIOS(
    INV_ID SERIAL PRIMARY KEY,
    INV_FECHA_HORA TIMESTAMP,
    INV_TOTAL INT,
    INV_USU_ID INT,
    INV_TIPO VARCHAR(50),
    INV_OBSERVACIONES TEXT,
    CHECK(INV_TIPO IN('ENTRADA','SALIDA')),
    FOREIGN KEY(INV_USU_ID) REFERENCES USUARIOS(USU_ID)
);

CREATE TABLE DETALLE_INVENTARIOS(
    DET_INV_ID SERIAL PRIMARY KEY,
    DET_INV_INV_ID INT,
    DET_INV_PRO_ID INT,
    DET_INV_CANTIDAD NUMERIC(10,2),
    FOREIGN KEY(DET_INV_INV_ID) REFERENCES INVENTARIOS(INV_ID),
    FOREIGN KEY(DET_INV_PRO_ID) REFERENCES PRODUCTOS(PRO_ID)
);

